### PR TITLE
add fixes for Elixir 1.2 compiler warnings

### PR DESCRIPTION
**Pull request by jeffweiss**
Prior to this commit, ex_twilio was resulting in a compiler warning for
Elixir 1.2. This commit explicitly returns nil from the stream function
to mollify the compiler. This commit also updates various dependencies.

### CODE REVIEW

**Comment by danielberkompas** [comment]
Thanks Jeff. I'll look into these conflicts.

**Comment by danielberkompas** [comment]
@jeffweiss Turns out I can really see what the conflicts are. Can you?

**Comment by jeffweiss** [comment]
@danielberkompas it was late and I, stupidly, branched from a much older version of master. I've rebased. It should be fine-ish now.

**Comment by danielberkompas** [comment]
Great, thanks! I'll release a new version when I can.

:star: :star:

**Pull request merged**
