### PR TITLE
Bump elixir version

### PR DESCRIPTION
**Pull request by enilsen16**
Httpoison as of 0.9.0 is supporting only elixir 1.2 and greater. I also bumped a httpoison and joken to their latest versions.

### CODE REVIEW

**Comment by enilsen16** [comment]
Tests seem to fail because PLTs for both versions of elixir/erlang do not exist.

**Comment by danielberkompas** [comment]
@enilsen16 merge `master` into your branch and try again. I've updated the travis configuration on `master` to run against Elixir 1.3.3.

**Comment by enilsen16** [comment]
Should be good to go now 😄

**Comment by danielberkompas** [comment]
@enilsen16 Thanks! :star:

**Pull request merged**
