### PR TITLE
[WIP] Add RTC Capability Tokens

### LINKED ISSUE #53: RTC Capability Grants
I noticed ExTwilio has support for signing call tokens, I'd like to expand this to support video calling as well.

To leverage the creation of tokens for Video ([docs](https://www.twilio.com/docs/api/video/guide/identity#client-initialize-the-sdk-with-an-access-token)),  tokens must be signed with a grant of `rtc`.

Ruby implementation: https://github.com/twilio/twilio-ruby/blob/0a945ccc1c536c711745b26b0023b1a75b132450/lib/twilio-ruby/util/access_token.rb#L55-L71

Documentation on Capability signing: https://www.twilio.com/docs/api/client/capability-token-spec

### PR DESCRIPTION
**Pull request by danielberkompas**
@stavro would you be able to test this?

Closes #53.

### CODE REVIEW

**Comment by stavro** [comment]
I can test this on Wednesday - if you'll wait!

**Comment by danielberkompas** [comment]
@stavro Did you get around to testing this?

**Comment by stavro** [comment]
I can't seem to get this to work as expected.

I've replaced my custom token generation with:

```elixir
identity
|> ExTwilio.Capability.allow_rtc()
|> ExTwilio.Capability.token()
```

But I get a configuration error when actually submitting the token to Twilio:

```json
{
  "message":"com.twilio.domain.auth.jwt.JwtAuthorizationException: 'cty' must be one of [twilio-fpa;v=1, twilio-sat;v=1], is null",
  "code":9102,
  "user_error":true,
  "params":{"requestId":"4fe5b540-96bc-4f06-a2ca-751b95d56b00"}
}
```

In my custom implementation I had to do this:

```elixir
payload
|> Joken.token()
|> Joken.with_header_arg("cty", "twilio-fpa;v=1")
|> Joken.with_signer(Joken.hs256(api_secret))
|> Joken.sign()
|> Joken.get_compact()
```

I'm not sure what this parameter is, but I couldn't get it working without it.

**Comment by stavro** [comment]
* cty is the content-type and encodes the version of the Access Token. It MUST be "twilio-fpa;v=1".

Source: https://www.twilio.com/docs/api/rest/access-tokens

**Pull request closed without merging**
